# -*- coding: utf-8 -*-
"""Worksheet_1_Solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHJEj5mEjobnIUUHUapfnmcm9cgzELvo

# Eshan Group of Institutions
"""

#try to write some code
print("Welcome to my Colab Notebook")

"""# Jobaaj.com
## Jobaaj.com
### Jobaaj.com

# **Eshan Group of Institutions**

# *Jobaaj.com*
## *Jobaaj.com*
### *Jobaaj.com*
